const ARTICLES = [
  {
    slug: 'best-email-marketing-tools-for-beginners',
    title: 'Best Email Marketing Tools for Beginners',
    topic: 'marketing',
    excerpt: 'Mailchimp, MailerLite, or Brevo? An honest comparison for UK small business owners who just want emails to go out without the faff.',
    date: '2026-05-09',
  },
  {
    slug: 'monday-com-review-for-small-business',
    title: 'Monday.com Review for Small Business',
    topic: 'productivity',
    excerpt: 'Monday.com is everywhere. But is it right for a small team or solo operator — or is the pricing model working against you?',
    date: '2026-05-09',
  },
  {
    slug: 'best-scheduling-tools-for-coaches',
    title: 'Best Scheduling Tools for Coaches',
    topic: 'coaching',
    excerpt: 'Calendly, Acuity, or Tidycal? A straight-talking guide for coaches who want clients to book without the back-and-forth.',
    date: '2026-05-09',
  },
  {
    slug: 'best-accounting-software-for-sole-traders-uk',
    title: 'Best Accounting Software for Sole Traders UK',
    topic: 'finance',
    excerpt: 'Xero, QuickBooks, or FreeAgent? An honest guide to accounting software for UK sole traders — with real pricing and no jargon.',
    date: '2026-05-09',
  },
  {
    slug: 'best-invoicing-software-for-small-business-uk',
    title: 'Best Invoicing Software for Small Business UK',
    topic: 'finance',
    excerpt: 'Stop chasing payments with spreadsheets. The best invoicing tools for UK small businesses — compared on features, price, and ease of use.',
    date: '2026-05-09',
  },
  {
    slug: 'best-project-management-tools-for-freelancers',
    title: 'Best Project Management Tools for Freelancers',
    topic: 'productivity',
    excerpt: 'When it\'s just you managing multiple clients, the right project management tool makes all the difference. Here\'s what actually works.',
    date: '2026-05-09',
  },
  {
    slug: 'canva-pro-review-is-the-upgrade-worth-it',
    title: 'Canva Pro Review: Is the Upgrade Worth It?',
    topic: 'marketing',
    excerpt: 'Canva\'s free plan is genuinely useful. But is Pro worth £10.99 a month for a small business? An honest look at what you actually get.',
    date: '2026-05-09',
  },
  {
    slug: 'freshbooks-vs-quickbooks-for-freelancers',
    title: 'FreshBooks vs QuickBooks for Freelancers',
    topic: 'finance',
    excerpt: 'Two of the most popular accounting tools for freelancers — but they suit very different working styles. Here\'s how to choose.',
    date: '2026-05-09',
  },
  {
    slug: 'monday-vs-asana-for-small-teams',
    title: 'Monday.com vs Asana for Small Teams',
    topic: 'productivity',
    excerpt: 'Both promise to fix your workflow. Monday.com is more flexible; Asana is more focused. Which one is actually right for a small team?',
    date: '2026-05-09',
  },
  {
    slug: 'notion-vs-obsidian-for-note-taking',
    title: 'Notion vs Obsidian for Note-Taking',
    topic: 'productivity',
    excerpt: 'Notion is collaborative and structured. Obsidian is private and powerful. The right choice depends on how your brain works.',
    date: '2026-05-09',
  },
  {
    slug: 'cheaper-alternatives-to-monday-com',
    title: 'Cheaper Alternatives to Monday.com for UK Small Teams',
    topic: 'productivity',
    excerpt: 'Monday.com is polished but pricey. These alternatives deliver the same core features for significantly less — some for free.',
    date: '2026-05-09',
  },
];